language: java
jdk:
  - oraclejdk8
maven: 
  version: 3.3.9
before_install:
  - git clone --branch=$TRAVIS_BRANCH https://github.com/know-share/KS-Data.git
  - cd KS-Data && mvn install
script: cd $TRAVIS_BUILD_DIR/ && mvn test -B
